"""Localization (English / Russian).

* ``tr(text, **kw)`` - the English source string is the key; the Russian translation lives
  in :mod:`app.i18n.ru`.  Placeholders use ``str.format`` syntax.
* ``n(count, noun)`` - number + correctly declined noun ("147 events" / "147 событий").
* ``num(value)`` - locale-aware thousands separator.

Enumerated values stored in the database (severity, category, assessment, status, kind)
always stay in English and are translated only for display.  Sentences generated by the
analysis (explanations, recommendations, reasons) are produced in the language that is
active when the analysis runs.
"""

from __future__ import annotations

import locale
import os
import sys

SUPPORTED = {"en": "English", "ru": "Русский"}
_lang = "en"


def set_language(lang: str | None) -> None:
    global _lang
    _lang = lang if lang in SUPPORTED else "en"


def get_language() -> str:
    return _lang


def _catalog() -> dict[str, str]:
    if _lang == "ru":
        from app.i18n.ru import RU
        return RU
    return {}


def tr(text: str, **kwargs) -> str:
    template = _catalog().get(text, text) if _lang != "en" else text
    if kwargs:
        try:
            return template.format(**kwargs)
        except (KeyError, IndexError, ValueError):
            return text.format(**kwargs)
    return template


def num(value) -> str:
    if value is None:
        return "-"
    if isinstance(value, float) and not value.is_integer():
        text = f"{value:,.1f}"
    else:
        text = f"{int(value):,}"
    return text.replace(",", " ") if _lang == "ru" else text


def _ru_form(count: int, forms: tuple[str, str, str]) -> str:
    count = abs(int(count))
    if count % 10 == 1 and count % 100 != 11:
        return forms[0]
    if 2 <= count % 10 <= 4 and not 12 <= count % 100 <= 14:
        return forms[1]
    return forms[2]


def n(count: int, noun: str) -> str:
    """'147 events' / '147 событий'. ``noun`` is the English singular key of :data:`NOUNS`."""
    entry = NOUNS.get(noun)
    if entry is None:
        return f"{num(count)} {noun if count == 1 else noun + 's'}"
    if _lang == "ru":
        return f"{num(count)} {_ru_form(count, entry[1])}"
    return f"{num(count)} {noun if count == 1 else entry[0]}"


# English singular -> (English plural, (Russian 1, 2-4, 5+))
NOUNS: dict[str, tuple[str, tuple[str, str, str]]] = {
    "event": ("events", ("событие", "события", "событий")),
    "account": ("accounts", ("учётная запись", "учётные записи", "учётных записей")),
    "host": ("hosts", ("хост", "хоста", "хостов")),
    "incident": ("incidents", ("инцидент", "инцидента", "инцидентов")),
    "change": ("changes", ("изменение", "изменения", "изменений")),
    "failed authentication attempt": ("failed authentication attempts",
                                      ("неудачная попытка аутентификации", "неудачные попытки аутентификации",
                                       "неудачных попыток аутентификации")),
    "successful authentication": ("successful authentications",
                                  ("успешная аутентификация", "успешные аутентификации", "успешных аутентификаций")),
    "privileged action": ("privileged actions",
                          ("привилегированное действие", "привилегированных действия",
                           "привилегированных действий")),
    "malicious web request": ("malicious web requests",
                              ("вредоносный веб-запрос", "вредоносных веб-запроса", "вредоносных веб-запросов")),
    "network event": ("network events", ("сетевое событие", "сетевых события", "сетевых событий")),
    "authentication event": ("authentication events",
                             ("событие аутентификации", "события аутентификации", "событий аутентификации")),
    "scan event": ("scan events", ("событие сканирования", "события сканирования", "событий сканирования")),
    "malware finding": ("malware findings",
                        ("обнаружение вредоносного ПО", "обнаружения вредоносного ПО",
                         "обнаружений вредоносного ПО")),
    "monitored host": ("monitored hosts", ("контролируемый хост", "контролируемых хоста", "контролируемых хостов")),
    "security event": ("security events", ("событие безопасности", "события безопасности",
                                           "событий безопасности")),
    "critical/high event": ("critical/high events", ("критическое/высокое событие", "критических/высоких события",
                                                     "критических/высоких событий")),
    "finding": ("findings", ("находка", "находки", "находок")),
    "file": ("files", ("файл", "файла", "файлов")),
    "malformed record": ("malformed records", ("повреждённая запись", "повреждённые записи",
                                               "повреждённых записей")),
}

# Display labels for enumerated values stored in English.
_ENUM_LABELS = {
    "critical": "Critical", "high": "High", "medium": "Medium", "low": "Low", "informational": "Informational",
}


def severity_label(severity: str, upper: bool = True) -> str:
    text = tr(_ENUM_LABELS.get((severity or "").lower(), severity or ""))
    return text.upper() if upper else text


def detect_system_language() -> str:
    """Best-effort OS UI language detection (used for the first-run default)."""
    override = os.environ.get("WSA_LANGUAGE", "").lower()
    if override in SUPPORTED:
        return override
    try:
        if sys.platform == "win32":
            import ctypes
            lang_id = ctypes.windll.kernel32.GetUserDefaultUILanguage()  # type: ignore[attr-defined]
            if lang_id & 0x3FF == 0x19:  # LANG_RUSSIAN
                return "ru"
            return "en"
        value = os.environ.get("LANG") or (locale.getlocale()[0] or "")
        return "ru" if value.lower().startswith("ru") else "en"
    except Exception:
        return "en"
